"""HTML Report Generator for Wappalyzer scan results."""
import datetime


def generate_report(url: str, technologies: list, scan_data: dict) -> str:
    """Generate an HTML technology intelligence report from Wappalyzer results."""
    domain = url.split("://")[-1].split("/")[0]

    # Group by category
    categories = scan_data.get("categories", {})
    # Also categorize from technologies list
    cat_map = {}
    for t in technologies:
        for cat in t.get("categories", []):
            if cat not in cat_map:
                cat_map[cat] = []
            cat_map[cat].append(t["name"])

    # Use Wappalyzer categories if available, otherwise build from techs
    display_cats = categories if categories else cat_map

    # Build HTML table
    cat_rows = ""
    for cat_name in sorted(display_cats.keys()):
        tech_list = display_cats[cat_name]
        if not isinstance(tech_list, list):
            continue
        cat_rows += '<tr><td colspan="3" style="background:rgba(124,58,237,0.08);padding:8px 12px;font-weight:600;color:#a78bfa">%s</td></tr>' % cat_name
        for t in tech_list:
            # Find version if available
            ver = ""
            for tt in technologies:
                if tt["name"] == t:
                    ver = tt.get("version", "")
                    break
            ver_str = " (v%s)" % ver if ver else ""
            cat_rows += '<tr><td style="padding:8px 12px;border-bottom:1px solid #1e293b">%s%s</td>' % (t, ver_str)
            cat_rows += '<td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#34d399;font-weight:600">Detected</td>'
            cat_rows += '<td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#8892a4">Wappalyzer</td></tr>'

    total = len(technologies)
    cat_count = len(display_cats)
    title = scan_data.get("title", domain)
    status = scan_data.get("status_code", 0)

    return """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8">
<title>Technology Report - %s</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#0b1121;color:#e8edf5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif;padding:40px 20px}
.report{max-width:800px;margin:0 auto}
.header{text-align:center;padding:40px 0;border-bottom:1px solid rgba(255,255,255,0.08);margin-bottom:30px}
.header h1{font-size:1.8rem;font-weight:700;background:linear-gradient(135deg,#c4b5fd,#7c3aed);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.header .domain{font-size:1.2rem;color:#e8edf5;margin:8px 0}
.header .meta{color:#8892a4;font-size:0.85rem}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:28px}
.stat-card{background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06);border-radius:10px;padding:16px;text-align:center}
.stat-card .val{font-size:1.8rem;font-weight:700;color:#7c3aed}
.stat-card .lbl{font-size:0.8rem;color:#8892a4;margin-top:4px}
table{width:100%;border-collapse:collapse;font-size:0.9rem;margin-bottom:28px}
th{text-align:left;color:#8892a4;padding:8px 12px;border-bottom:1px solid #1e293b;font-weight:500;font-size:0.8rem;text-transform:uppercase}
.section h2{font-size:1.1rem;font-weight:600;margin-bottom:14px;color:#c4b5fd}
.footer{border-top:1px solid rgba(255,255,255,0.08);padding:20px 0;text-align:center;color:#5a6474;font-size:0.8rem;margin-top:30px}
.footer a{color:#a78bfa;text-decoration:none}
.summary-box{background:rgba(124,58,237,0.06);border:1px solid rgba(124,58,237,0.15);border-radius:10px;padding:18px;margin-bottom:24px}
.summary-box p{color:#8892a4;font-size:0.9rem;line-height:1.5}
</style>
</head>
<body>
<div class="report">
<div class="header">
<h1>Technology Intelligence Report</h1>
<div class="domain">%s</div>
<div class="meta">%s &middot; HTTP %s &middot; %s</div>
</div>
<div class="stats">
<div class="stat-card"><div class="val">%d</div><div class="lbl">Technologies</div></div>
<div class="stat-card"><div class="val">%d</div><div class="lbl">Categories</div></div>
<div class="stat-card"><div class="val">%s</div><div class="lbl">Engine</div></div>
</div>
<div class="section"><h2>Detected Technologies <span style="font-size:0.7rem;color:#8892a4">powered by Wappalyzer (7,245 fingerprints)</span></h2>
<table><thead><tr><th>Technology</th><th>Status</th><th>Source</th></tr></thead><tbody>
%s
</tbody></table></div>
<div class="summary-box">
<p><strong>Summary:</strong> %s uses %d technologies across %d categories.</p>
</div>
<div class="footer">
Generated by <a href="https://github.com/biuta666/techstack-analyzer">TechStack Analyzer v2.0</a> &middot; Powered by Wappalyzer (7,245 fingerprints) &middot; <a href="https://github.com/biuta666/geocheck">GEOCheck</a>
</div>
</div>
</body>
</html>""" % (
        domain,
        domain, title, status, datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        total, cat_count, "Wappalyzer",
        cat_rows,
        domain, total, cat_count,
    )
